var squares = ["Eye Patch",
"Guy Mullet",
"Camouflage",
"Giant Belt Buckle",
"Mother/Daughter Skanks",
"Overalls",
"Cowboy Hat",
"Tattooed Boob",
"Boobs about to fall out",
"Mohawk",
"Man Pony Tail",
"Old Person Grinding on Dance Floor",
"Skunk Hair",
"Pregnant Chick",
"Booty Grinding Dancing",
"Female Mullet",
"Fishnet Hose",
"Raw Hide Clothing",
"Sequined Gown",
"Bandana",
"Teased 80's Hair",
"Dolly Parton Look-Alike",
"NASCAR Jacket",
"Member's Only Jacket",
"Fur Coat",
"Clip-on Chains",
"Micro Mini that should never",
"Boots with Fur",
"Man Camel Toe",
"Female Camel Toe",
"Obvious Fake Boobs",
"Really Spiked Hair",
"Man w/3 or more open shirt buttons",
"Civil War Hat",
"Bad Rug",
"Leather Hat w/Studs",
"That Bitch",
"Gravity Defying Tube Top",
"Pimp Hat/Outfit",
"Missing Teeth",
"Leather Pants",
"Dreads",
"Skinny Jeans",
"Big Ole Booty",
"Facial Piercing",
"Neck Beard",
"Inappropriate Display of Affection"];
